### ISSUE TITLE
Month error on choosing from options

### ISSUE THREAD

**Issue by joyadeep** [rohanAdhikari1/react-nepali-datepicker#1]
When date from different month is selected, date month is completely different. 
month is supposed to be between [1-12] but it can go beyond that.

**Comment by rohanAdhikari1** [comment]
Thank you for reporting this issue. I acknowledge the problem with the date selection where the month can exceed the expected range of 1-12.
I will investigate the code to identify why the month can exceed the expected range and propose a fix.

**Comment by rohanAdhikari1** [comment]
Thank you for bringing this issue to our attention. I'm pleased to inform you that we've fixed the problem regarding the date selection. Now, the month is appropriately restricted to the range of 1-12 as expected.

If you encounter any further issues or have any additional feedback, please don't hesitate to let me know. Thank you for your patience.

**Comment by joyadeep** [comment]
Thank you for taking immediate action. But the issue has not been resolved completely.
As you can see in below image, date is shown accurate, but its value is different like previous.
when you try to console value from onSelect this error is seen.
`onSelect={(date:string)=>{console.log("from date ==",date)}}`
 

![issue](https://github.com/rohanAdhikari1/react-nepali-datepicker/assets/34575085/662da985-83b6-49be-aa4d-0940f7570d8d)

**Comment by rohanAdhikari1** [comment]
Thank you for your prompt attention to this matter. I appreciate your patience as I work to address the issue further.

Regarding the reported problem with the date value not matching the expected output, I have updated the project to version 0.1.0 as requested. Kindly try again with this updated version.

However, it seems that the issue persists, particularly when attempting to log the date value from the onSelect event. I apologize for any inconvenience this may have caused.

To better assist you, could you please provide more details or steps to reproduce the problem? Additionally, if there are any error messages or console logs associated with this issue, please share them with me so that I can investigate further and provide a more accurate solution.

Thank you for your continued cooperation.

Best regards,
React Nepali Date Picker Author
Rohan Adhikari

**Comment by joyadeep** [comment]
Thank you for your prompt attention to this matter and for the update on the issue resolution.
With the latest version 0.1.0 of the React Nepali Date Picker my issues has been solved and i am closing this issue. Your efforts are greatly appreciated.
Thank you once again for your dedication to maintaining this project.
